import type { Product, Category } from "@/types";

export const categories: Category[] = [
  { id: "c1", name: "Electronics", slug: "electronics", icon: "Smartphone", productCount: 1240 },
  { id: "c2", name: "Fashion", slug: "fashion", icon: "Shirt", productCount: 3450 },
  { id: "c3", name: "Home & Living", slug: "home-living", icon: "Home", productCount: 890 },
  { id: "c4", name: "Beauty & Health", slug: "beauty-health", icon: "Heart", productCount: 670 },
  { id: "c5", name: "Sports & Outdoors", slug: "sports-outdoors", icon: "Dumbbell", productCount: 450 },
  { id: "c6", name: "Groceries", slug: "groceries", icon: "Apple", productCount: 2100 },
  { id: "c7", name: "Toys & Kids", slug: "toys-kids", icon: "Gamepad2", productCount: 380 },
  { id: "c8", name: "Automotive", slug: "automotive", icon: "Car", productCount: 290 },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Samsung Galaxy A54 5G 128GB",
    description: "Stunning 6.4\" Super AMOLED display, 50MP camera, 5000mAh battery. Experience flagship features at an incredible price.",
    price: 42900,
    oldPrice: 48900,
    image: "https://images.unsplash.com/photo-1610945265078-3858a0828671?w=400&h=400&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1610945265078-3858a0828671?w=400&h=400&fit=crop",
    ],
    category: "electronics",
    subcategory: "Phones",
    rating: 4.6,
    reviews: 342,
    reviewCount: 342,
    stock: 45,
    vendor: "TechWorld Kenya",
    vendorId: "v1",
    badges: ["Best Seller", "Free Shipping"],
    isDeal: true,
    dealEnds: "2026-06-26T23:59:59Z",
    freeShipping: true,
    shipping: "Free",
    sku: "SG-A54-128",
    tags: ["samsung", "galaxy", "smartphone", "5g", "android", "mobile"],
  },
  {
    id: "p2",
    name: "HP 15s Laptop Intel Core i5",
    description: "15.6\" FHD display, 8GB RAM, 512GB SSD. Perfect for work and study with all-day battery life.",
    price: 58900,
    oldPrice: 65000,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
    category: "electronics",
    subcategory: "Laptops",
    rating: 4.4,
    reviews: 189,
    reviewCount: 189,
    stock: 23,
    vendor: "Digital Hub",
    vendorId: "v2",
    badges: ["Flash Deal"],
    isDeal: true,
    dealEnds: "2026-06-25T23:59:59Z",
    freeShipping: true,
    shipping: "Free",
    sku: "HP-15S-I5",
    tags: ["hp", "laptop", "intel", "core i5", "computer", "notebook"],
  },
  {
    id: "p3",
    name: "Sony WH-1000XM5 Wireless Headphones",
    description: "Industry-leading noise cancellation, 30-hour battery life, premium comfort for all-day wear.",
    price: 34500,
    oldPrice: 42000,
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&h=400&fit=crop",
    category: "electronics",
    subcategory: "Audio",
    rating: 4.8,
    reviews: 567,
    reviewCount: 567,
    stock: 12,
    vendor: "AudioMax Store",
    vendorId: "v3",
    badges: ["Top Rated"],
    isDeal: true,
    dealEnds: "2026-06-26T23:59:59Z",
    freeShipping: false,
    shipping: "200",
    sku: "SNY-WH1000XM5",
    tags: ["sony", "headphones", "wireless", "noise cancelling", "audio", "bluetooth"],
  },
  {
    id: "p4",
    name: "Nike Air Force 1 '07 White",
    description: "Iconic style meets everyday comfort. Leather upper, Air-Sole cushioning, timeless design.",
    price: 11500,
    oldPrice: 13900,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop",
    category: "fashion",
    subcategory: "Shoes",
    rating: 4.7,
    reviews: 892,
    reviewCount: 892,
    stock: 78,
    vendor: "SneakerLab Nairobi",
    vendorId: "v4",
    badges: ["Trending"],
    isDeal: true,
    dealEnds: "2026-06-27T23:59:59Z",
    freeShipping: false,
    shipping: "300",
    sku: "NK-AF1-WHT",
    tags: ["nike", "air force", "sneakers", "shoes", "white", "casual"],
  },
  {
    id: "p5",
    name: "Ankara Print Maxi Dress",
    description: "Vibrant African wax print, flowing maxi length, perfect for celebrations and special occasions.",
    price: 3200,
    oldPrice: 4500,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop",
    category: "fashion",
    subcategory: "Dresses",
    rating: 4.5,
    reviews: 234,
    reviewCount: 234,
    stock: 34,
    vendor: "Swahili Fashion House",
    vendorId: "v5",
    badges: ["Made in Kenya"],
    freeShipping: false,
    shipping: "250",
    sku: "SF-ANK-MAXI",
    tags: ["ankara", "dress", "african print", "fashion", "women", "maxi"],
  },
  {
    id: "p6",
    name: "Men's Slim Fit Chino Pants",
    description: "Classic slim fit chinos in versatile colors. Cotton stretch blend for all-day comfort.",
    price: 2800,
    oldPrice: 3500,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=400&fit=crop",
    category: "fashion",
    subcategory: "Pants",
    rating: 4.3,
    reviews: 156,
    reviewCount: 156,
    stock: 89,
    vendor: "Urban Style Co",
    vendorId: "v6",
    freeShipping: false,
    shipping: "250",
    sku: "US-CHINO-SLM",
    tags: ["chinos", "pants", "men", "slim fit", "casual", "trousers"],
  },
  {
    id: "p7",
    name: "Samsung 55\" Crystal UHD 4K Smart TV",
    description: "Crystal Processor 4K, HDR, built-in streaming apps. Transform your living room entertainment.",
    price: 62900,
    oldPrice: 74900,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop",
    category: "electronics",
    subcategory: "TV",
    rating: 4.5,
    reviews: 278,
    reviewCount: 278,
    stock: 15,
    vendor: "ElectroMart",
    vendorId: "v7",
    badges: ["Big Save"],
    isDeal: true,
    dealEnds: "2026-06-25T23:59:59Z",
    freeShipping: false,
    shipping: "500",
    sku: "SAM-55CUHD",
    tags: ["samsung", "tv", "4k", "smart tv", "crystal uhd", "television"],
  },
  {
    id: "p8",
    name: "Dyson V12 Detect Slim Vacuum",
    description: "Laser dust detection, powerful suction, lightweight design. The ultimate cleaning companion.",
    price: 78500,
    oldPrice: 89000,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&h=400&fit=crop",
    category: "home-living",
    subcategory: "Appliances",
    rating: 4.9,
    reviews: 134,
    reviewCount: 134,
    stock: 8,
    vendor: "Home Essentials",
    vendorId: "v8",
    badges: ["Premium"],
    isDeal: true,
    dealEnds: "2026-06-26T23:59:59Z",
    freeShipping: true,
    shipping: "Free",
    sku: "DY-V12-SLM",
    tags: ["dyson", "vacuum", "cleaner", "home", "appliance", "cordless"],
  },
  {
    id: "p9",
    name: "Ceramic Cookware Set 8-Piece",
    description: "Non-stick ceramic coating, even heat distribution, oven-safe up to 450°F. Cook healthier meals.",
    price: 8900,
    oldPrice: 12000,
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&h=400&fit=crop",
    category: "home-living",
    subcategory: "Kitchen",
    rating: 4.4,
    reviews: 312,
    reviewCount: 312,
    stock: 56,
    vendor: "KitchenMaster",
    vendorId: "v9",
    badges: ["Hot Deal"],
    isDeal: true,
    dealEnds: "2026-06-27T23:59:59Z",
    freeShipping: false,
    shipping: "400",
    sku: "KM-CER-8PC",
    tags: ["cookware", "ceramic", "kitchen", "pots", "pans", "cooking"],
  },
  {
    id: "p10",
    name: "CeraVe Moisturizing Cream 454g",
    description: "Dermatologist-developed, ceramide-rich formula for 24-hour hydration. Suitable for face and body.",
    price: 1850,
    oldPrice: 2400,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop",
    category: "beauty-health",
    subcategory: "Skincare",
    rating: 4.8,
    reviews: 723,
    reviewCount: 723,
    stock: 120,
    vendor: "Glow Pharmacy",
    vendorId: "v10",
    badges: ["Best Seller"],
    freeShipping: false,
    shipping: "150",
    sku: "CV-MC-454",
    tags: ["cerave", "moisturizer", "skincare", "cream", "beauty", "hydration"],
  },
  {
    id: "p11",
    name: "Whey Protein Isolate 2kg",
    description: "25g protein per serving, low carb, chocolate flavor. Fuel your workouts and recovery.",
    price: 5600,
    oldPrice: 7200,
    image: "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400&h=400&fit=crop",
    category: "sports-outdoors",
    subcategory: "Supplements",
    rating: 4.6,
    reviews: 445,
    reviewCount: 445,
    stock: 67,
    vendor: "FitLife Nutrition",
    vendorId: "v11",
    badges: ["Popular"],
    freeShipping: false,
    shipping: "300",
    sku: "FL-WPI-2KG",
    tags: ["protein", "whey", "fitness", "gym", "supplement", "nutrition"],
  },
  {
    id: "p12",
    name: "Yoga Mat Premium 6mm",
    description: "Extra thick cushioning, non-slip surface, eco-friendly TPE material. Perfect for any practice.",
    price: 2200,
    oldPrice: 3200,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop",
    category: "sports-outdoors",
    subcategory: "Fitness",
    rating: 4.5,
    reviews: 289,
    reviewCount: 289,
    stock: 94,
    vendor: "Zen Fitness",
    vendorId: "v12",
    badges: ["Eco Friendly"],
    freeShipping: false,
    shipping: "250",
    sku: "ZF-YMAT-6MM",
    tags: ["yoga", "mat", "fitness", "exercise", "gym", "workout"],
  },
  {
    id: "p13",
    name: "Organic Basmati Rice 5kg",
    description: "Aged premium basmati, aromatic long grains. Perfect for biryanis and daily meals.",
    price: 850,
    oldPrice: 1100,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop",
    category: "groceries",
    subcategory: "Grains",
    rating: 4.3,
    reviews: 567,
    reviewCount: 567,
    stock: 200,
    vendor: "FreshMart Kenya",
    vendorId: "v13",
    badges: ["Organic"],
    freeShipping: false,
    shipping: "200",
    sku: "FM-BAS-5KG",
    tags: ["rice", "basmati", "organic", "food", "groceries", "grain"],
  },
  {
    id: "p14",
    name: "Cold Pressed Coconut Oil 1L",
    description: "100% pure, virgin coconut oil. Multi-purpose for cooking, hair, and skincare.",
    price: 1200,
    oldPrice: 1600,
    image: "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?w=400&h=400&fit=crop",
    category: "groceries",
    subcategory: "Oils",
    rating: 4.7,
    reviews: 423,
    reviewCount: 423,
    stock: 150,
    vendor: "Nature's Best",
    vendorId: "v14",
    badges: ["Pure"],
    freeShipping: false,
    shipping: "200",
    sku: "NB-CCO-1L",
    tags: ["coconut oil", "organic", "cooking", "hair", "skincare", "natural"],
  },
  {
    id: "p15",
    name: "LEGO Star Wars X-Wing Fighter",
    description: "Build the legendary starfighter with 474 pieces. Includes Luke Skywalker minifigure.",
    price: 7800,
    oldPrice: 9500,
    image: "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=400&h=400&fit=crop",
    category: "toys-kids",
    subcategory: "Building Sets",
    rating: 4.9,
    reviews: 198,
    reviewCount: 198,
    stock: 31,
    vendor: "Toy Kingdom",
    vendorId: "v15",
    badges: ["Award Winner"],
    freeShipping: false,
    shipping: "300",
    sku: "TK-LSW-XWF",
    tags: ["lego", "star wars", "toys", "building", "kids", "blocks"],
  },
  {
    id: "p16",
    name: "Car Vacuum Cleaner 12V",
    description: "Powerful handheld vacuum, multiple attachments, 5m power cord. Keep your car spotless.",
    price: 1950,
    oldPrice: 2800,
    image: "https://images.unsplash.com/photo-1520340356584-4bb7ff2fa7c7?w=400&h=400&fit=crop",
    category: "automotive",
    subcategory: "Accessories",
    rating: 4.2,
    reviews: 312,
    reviewCount: 312,
    stock: 76,
    vendor: "AutoZone Kenya",
    vendorId: "v16",
    badges: ["Useful"],
    freeShipping: false,
    shipping: "200",
    sku: "AZ-CVC-12V",
    tags: ["car", "vacuum", "automotive", "cleaner", "accessory", "12v"],
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getDealProducts(): Product[] {
  return products.filter((p) => p.isDeal);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.vendor.toLowerCase().includes(q)
  );
}

export function formatPrice(price: number): string {
  return "KSh " + price.toLocaleString("en-KE");
}

export function calculateDiscount(price: number, oldPrice?: number): number {
  if (!oldPrice || oldPrice <= price) return 0;
  return Math.round(((oldPrice - price) / oldPrice) * 100);
}